{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zebra-agent.serviceAccountName" . }}
  labels:
    {{- include "zebra-agent.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
