export default {
  today: "最近",
  yesterday: "归档",
  newConversation: "新任务",
  delete: "删除",
  noData: "暂无返回",
  agentName: "Zebra Agent",
  placeholder: "描述任务，或粘贴报错。",
  pinned: "置顶",
  recent: "最近",
  projects: "项目",
  unboundProject: "未绑定工作区",
  newTaskTarget: "新任务目标",
  tasks: "个任务",
  noRecentSessions: "暂无任务",
  recentHint: "发起一条新任务后，这里会显示新的执行线程。",
  workspaceUnbound: "工作区未绑定",
  profileName: "Workspace Operator",
  workspaceBadge: "工作区",
  runtimeConnected: "本地运行时已连接",
  runtimeChecking: "正在检查本地运行时",
  runtimeDisconnected: "本地运行时未连接",
  runtimeSettings: "运行配置",
  copyWorkspacePath: "复制工作区路径",
  copySessionId: "复制会话 ID",
  refreshConversation: "刷新当前线程",
  scrollToLatest: "滚动到最新",
  closeArtifactPanel: "关闭产物详情",
  sessionIdCopied: "会话 ID 已复制",
  workspacePathCopied: "工作区路径已复制",
  filesTouched: "已触达文件",
  commandsRun: "执行命令",
  validationNotes: "校验摘要",
  workspaceChanges: "工作区变更",
  noWorkspaceChanges: "当前还没有可展示的工作区变更。",
  generatedArtifacts: "生成产物",
  noArtifactsYet: "当前会话还没有可读产物。",
  deliveryRecords: "交付记录",
  noDeliveryRecords: "当前还没有 commit / PR 交付记录。",
  idleProjectName: "zebra-agent",
  idlePromptTitle: "下一步任务",
  idlePromptSubtitle: "当前项目已就绪，可以开始一个本地工程任务。",
  suggestedActions: "建议操作",
  recentThreads: "最近任务",
  todayGroup: "今天",
  continueTasks: "继续任务",
  threadDraft: "任务草稿",
  notStarted: "尚未开始执行",
  threadComposerHint: "继续描述任务，或点击执行。",
  inspectorContext: "上下文",
  inspectorFiles: "文件",
  inspectorLogs: "日志",
  inspectorChanges: "变更",
  inspectorEmpty: "等待任务启动后生成。",
  threadTimeline: "任务时间线",
  eventsRecorded: "条事件已记录",
  stagePending: "等待执行",
  project: "项目",
  workspace: "工作区",
  policy: "权限策略",
  attempt: "执行轮次",
  sequence: "事件序号",
  notBound: "未绑定",
  noLogsYet: "当前还没有执行日志。",
  gitStatus: "Git 状态",
  changedFiles: "变更文件",
  stagePlanning: "Planning",
  stageReading: "Reading files",
  stageRunning: "Running command",
  stageEditing: "Editing files",
  stageTesting: "Testing",
  stageCompleted: "Completed",
  stageReview: "Review",
  hintDocs: "阅读文档",
  hintExplain: "解释项目结构",
  hintDebug: "定位问题",
  hintImplement: "实现功能",
  hintShip: "编写测试",
  hintReview: "审查变更",
  hintCommit: "创建提交",
  modeAsk: "问答",
  modeAct: "执行",
  attach: "附件",
  accessWorkspaceWrite: "权限: 工作区写入",
  modelDeepSeek: "模型: DeepSeek",
  statusDraft: "草稿",
  statusReady: "已就绪",
  statusRunning: "执行中",
  statusWaiting: "待确认",
  statusReview: "待审查",
  statusDone: "已完成",
  statusFailed: "失败",
  statusStopped: "已停止",
  suspendSession: "暂停会话",
  resumeSession: "恢复会话",
  cancelSession: "取消会话",
  modelLabel: "Zebra Agent · DeepSeek",
  generating: "执行中",
};
