export default {
  today: "最近",
  yesterday: "归档",
  newConversation: "新任务",
  deleteDraft: "删除本地草稿",
  hideTask: "隐藏任务",
  restoreHiddenTasks: "恢复已隐藏任务",
  agentName: "Zebra Agent",
  placeholder: "描述目标，或粘贴需要处理的内容。",
  pinned: "置顶",
  recent: "最近",
  projects: "项目",
  unboundProject: "未绑定工作区",
  newTaskTarget: "新任务目标",
  tasks: "个任务",
  noRecentSessions: "暂无任务",
  recentHint: "发起一条新任务后，这里会显示新的执行线程。",
  workspaceUnbound: "工作区未绑定",
  profileName: "Agent Operator",
  workspaceBadge: "工作区",
  runtimeConnected: "本地运行时已连接",
  runtimeChecking: "正在检查本地运行时",
  runtimeDisconnected: "本地运行时未连接",
  runtimeSettings: "运行配置",
  copyWorkspacePath: "复制工作区路径",
  copySessionId: "复制任务 ID",
  refreshConversation: "刷新当前线程",
  scrollToLatest: "滚动到最新",
  closeArtifactPanel: "关闭产物详情",
  sessionIdCopied: "任务 ID 已复制",
  workspacePathCopied: "工作区路径已复制",
  filesTouched: "已触达文件",
  commandsRun: "执行命令",
  validationNotes: "校验摘要",
  workspaceChanges: "工作区变更",
  noWorkspaceChanges: "当前还没有可展示的工作区变更。",
  generatedArtifacts: "生成产物",
  noArtifactsYet: "当前会话还没有可读产物。",
  deliveryRecords: "交付记录",
  noDeliveryRecords: "当前还没有 commit / PR 交付记录。",
  idlePromptTitle: "下一步任务",
  idlePromptSubtitle: "当前工作空间已就绪，可以开始一个 Agent 任务。",
  executionEnvironment: "执行环境",
  envWorkspace: "工作区",
  envPermission: "权限",
  envCapability: "能力",
  envNetwork: "网络",
  envLockedHint: "环境已随任务锁定",
  envAccessFull: "完整访问",
  envAccessWrite: "工作区写入",
  envToolCoding: "编码工具",
  envToolGeneral: "通用工具",
  suggestedActions: "建议操作",
  recentThreads: "最近任务",
  todayGroup: "今天",
  continueTasks: "继续任务",
  threadDraft: "任务草稿",
  notStarted: "尚未开始执行",
  threadComposerHint: "继续描述任务，或点击执行。",
  inspectorContext: "上下文",
  inspectorFiles: "文件",
  inspectorLogs: "日志",
  inspectorChanges: "变更",
  inspectorEmpty: "等待任务启动后生成。",
  threadTimeline: "任务时间线",
  eventsRecorded: "条事件已记录",
  stagePending: "等待执行",
  project: "项目",
  workspace: "工作区",
  policy: "权限策略",
  attempt: "执行轮次",
  sequence: "事件序号",
  notBound: "未绑定",
  noLogsYet: "当前还没有执行日志。",
  gitStatus: "Git 状态",
  changedFiles: "变更文件",
  stagePlanning: "Planning",
  stageContext: "Gathering context",
  stageTools: "Using tools",
  stageResult: "Producing result",
  stageVerification: "Verifying",
  stageCompleted: "Completed",
  stageReview: "Review",
  hintDocs: "总结资料",
  hintExplain: "解释上下文",
  hintDebug: "分析问题",
  hintImplement: "执行任务",
  hintShip: "验证结果",
  modeAsk: "问答",
  modeAct: "执行",
  attach: "附件",
  accessWorkspaceWrite: "权限: 工作区写入",
  modelDeepSeek: "模型: DeepSeek",
  statusDraft: "草稿",
  statusReady: "已就绪",
  statusRunning: "执行中",
  statusSuspended: "已暂停",
  statusWaiting: "待确认",
  statusWaitingInput: "待补充",
  statusReview: "待审查",
  statusDone: "已完成",
  statusFailed: "失败",
  statusStopped: "已停止",
  suspendSession: "暂停会话",
  resumeSession: "恢复会话",
  cancelSession: "取消会话",
  modelLabel: "Zebra Agent · DeepSeek",
};
