"""Opt-in real PG + owned Docker containers; no original runtime or volume mutation."""

import json
import os
import re
import subprocess
from uuid import uuid4

import psycopg
import pytest
from agent_runtime.adapters.oci_engine import PinnedOciEngine
from agent_runtime.command_runtime_cleanup import cleanup_runtime_batch
from agent_storage.postgres.direct_control import PostgresDirectControl
from psycopg.conninfo import make_conninfo

from tests.agent_storage.test_postgres_command_wakeup import NAMESPACE
from tests.agent_storage.test_postgres_command_wakeup import dsn as _dsn_fixture
from tests.agent_storage.test_postgres_command_wakeup import postgres_dsn as _pg_fixture
from tests.agent_storage.test_postgres_command_wakeup_control import _control, _intent
from tests.agent_storage.test_postgres_direct_control import WORKSPACE
from tests.agent_storage.test_postgres_runtime_instances import SCOPE, _instances, _setup
from tests.compose.rabbitmq_product_e2e.fixture import (
    OUTER_DOCKER_ENDPOINT,
    captured,
    host_environment,
)

dsn = _dsn_fixture
postgres_dsn = _pg_fixture
pytestmark = pytest.mark.skipif(
    os.environ.get("ZEBRA_RUNTIME_CLEANUP_LIVE") != "1",
    reason="set ZEBRA_RUNTIME_CLEANUP_LIVE=1 for owned Docker cleanup acceptance",
)


@pytest.fixture
def engine(dsn):
    # captured rechecks the approved local Docker context before resolving an image.
    image = captured(["docker", "image", "inspect", "--format", "{{.Id}}", "alpine:3.20"]).strip()
    assert re.fullmatch(r"sha256:[0-9a-f]{64}", image)
    application = f"cleanup-live-{uuid4()}"
    worker_dsn = make_conninfo(dsn, application_name=application)
    marker = str(uuid4())
    names = []

    def invoke(command, **kwargs):
        with psycopg.connect(dsn, autocommit=True) as observer:
            assert (
                observer.execute(
                    "SELECT count(*) FROM pg_stat_activity WHERE application_name=%s "
                    "AND xact_start IS NOT NULL",
                    (application,),
                ).fetchone()[0]
                == 0
            ), "engine IO ran inside a cleanup transaction"
        return subprocess.run(command, **kwargs)

    pinned = PinnedOciEngine(
        "docker",
        env={**host_environment(), "DOCKER_HOST": OUTER_DOCKER_ENDPOINT},
        runner=invoke,
    )

    def call(*command):
        return pinned(
            ("docker", *command),
            capture_output=True,
            text=True,
            check=False,
            timeout=20,
        )

    def create(instance_id, labels):
        name = f"zebra-{instance_id}"
        names.append(name)
        args = [
            "create",
            "--pull=never",
            "--name",
            name,
            "--network=none",
            "--read-only",
            "--cap-drop=ALL",
            "--security-opt=no-new-privileges",
            "--pids-limit=8",
            "--memory=16m",
            "--user=65534:65534",
            "--label",
            f"zebra.cleanup.acceptance={marker}",
        ]
        for key, value in labels.items():
            args.extend(("--label", f"{key}={value}"))
        result = call(*args, image, "sleep", "600")
        assert result.returncode == 0, "owned acceptance container creation failed"
        container_id = result.stdout.strip()
        assert re.fullmatch(r"[0-9a-f]{64}", container_id)
        assert call("start", container_id).returncode == 0
        return container_id

    try:
        yield pinned, worker_dsn, create, call
    finally:
        # Exact names were generated by this fixture. Verify its independent marker
        # before deleting a survivor; never sweep by Session or a broad label filter.
        for name in names:
            result = call("ps", "--all", "--no-trunc", "--quiet", "--filter", f"name=^{name}$")
            assert result.returncode == 0, "owned fixture teardown lookup failed"
            if not result.stdout.strip():
                continue
            container_id = result.stdout.strip()
            assert re.fullmatch(r"[0-9a-f]{64}", container_id)
            detail = call("inspect", "--format", "{{json .}}", container_id)
            assert detail.returncode == 0
            row = json.loads(detail.stdout)
            assert row["Id"] == container_id and row["Name"].lstrip("/") == name
            assert row["Config"]["Labels"]["zebra.cleanup.acceptance"] == marker
            assert call("rm", "--force", container_id).returncode == 0


@pytest.mark.parametrize(
    "case", ["created", "lost_created_write", "already_absent", "wrong_label", "direct_cancel"]
)
def test_exact_cleanup_after_cancel_with_real_engine_and_database(dsn, engine, case):
    pinned, worker_dsn, create, call = engine
    lease = _setup(dsn)
    instances = _instances(dsn, lease, engine=pinned.identity)
    instance_id = str(uuid4())
    labels = dict(instances.reserve(instance_id, str(lease.session_id), "cleanup-test-spec"))
    labels.update(
        {
            "zebra.agent.session": str(lease.session_id),
            "zebra.agent.spec": "cleanup-test-spec",
            "zebra.agent.runtime": "1",
        }
    )
    actual_labels = labels | ({"zebra.agent.scope": "other-owner"} if case == "wrong_label" else {})
    container_id = create(instance_id, actual_labels)
    if case != "lost_created_write":
        instances.created(instance_id, container_id)
    # An unrelated exact instance on the same engine must survive the cleanup.
    sibling_id = create(str(uuid4()), {"zebra.agent.session": str(lease.session_id)})
    if case == "already_absent":
        assert call("rm", "--force", container_id).returncode == 0
    if case == "direct_cancel":
        PostgresDirectControl(dsn, deployment_namespace=NAMESPACE).cancel(
            lease.session_id,
            scope=SCOPE,
            workspace_ref=WORKSPACE,
            idempotency_key="owned-live-direct-cancel",
        )
    else:
        command = _intent(dsn, lease.session_id, "cancel")
        _control(dsn, command)
    cleanup_runtime_batch(
        worker_dsn,
        deployment_namespace=NAMESPACE,
        owner="live-cleanup",
        engine=pinned,
    )
    with psycopg.connect(dsn) as connection:
        status = connection.execute(
            "SELECT status FROM runtime_instances WHERE instance_id=%s",
            (instance_id,),
        ).fetchone()[0]
        obligation = connection.execute("SELECT status FROM command_runtime_cleanup").fetchone()[0]
    remaining = call("ps", "--all", "--no-trunc", "--quiet", "--filter", f"id={container_id}")
    assert remaining.returncode == 0
    if case == "wrong_label":
        assert remaining.stdout.strip() == container_id
        assert status != "removed" and obligation != "done"
    else:
        assert remaining.stdout.strip() == ""
        assert status == "removed" and obligation == "done"
    assert call("inspect", "--format", "{{.State.Running}}", sibling_id).stdout.strip() == "true"


def test_empty_provisioning_lookup_retains_obligation_for_late_create(dsn, engine):
    pinned, worker_dsn, create, call = engine
    lease = _setup(dsn)
    instances = _instances(dsn, lease, engine=pinned.identity)
    instance_id = str(uuid4())
    labels = dict(instances.reserve(instance_id, str(lease.session_id), "late-create-spec"))
    labels.update(
        {
            "zebra.agent.session": str(lease.session_id),
            "zebra.agent.spec": "late-create-spec",
            "zebra.agent.runtime": "1",
        }
    )
    _control(dsn, _intent(dsn, lease.session_id, "cancel"))
    cleanup_runtime_batch(
        worker_dsn,
        deployment_namespace=NAMESPACE,
        owner="before-create",
        engine=pinned,
    )
    with psycopg.connect(dsn) as connection:
        assert connection.execute("SELECT status FROM runtime_instances").fetchone() == (
            "provisioning",
        )
        assert connection.execute("SELECT status FROM command_runtime_cleanup").fetchone() == (
            "pending",
        )
    # Simulate an already-issued create completing after cancellation. No worker
    # execution is resumed: only the independent test engine creates this target.
    container_id = create(instance_id, labels)
    instances.created(instance_id, container_id)
    with psycopg.connect(dsn) as connection:
        connection.execute("UPDATE command_runtime_cleanup SET available_at=clock_timestamp()")
    cleanup_runtime_batch(
        worker_dsn,
        deployment_namespace=NAMESPACE,
        owner="after-create",
        engine=pinned,
    )
    with psycopg.connect(dsn) as connection:
        assert connection.execute("SELECT status FROM runtime_instances").fetchone() == ("removed",)
        assert connection.execute("SELECT status FROM command_runtime_cleanup").fetchone() == (
            "done",
        )
    result = call("ps", "--all", "--no-trunc", "--quiet", "--filter", f"id={container_id}")
    assert result.returncode == 0 and not result.stdout.strip()
